name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit message joined
        env:
          COMMIT_MESSAGES_JOINED: ${{ toJson(join(github.event.commits.*.message, ',')) }}
        run: echo "$COMMIT_MESSAGES_JOINED"
      - name: commit messages joined contains
        env:
          COMMIT_MESSAGES_JOINED_CONTAINS: ${{ toJson(join(github.event.commits.*.message, ',').contains('#skip')) }}
        run: echo "$COMMIT_MESSAGES_JOINED_CONTAINS"
